#include <iostream>
#include <iomanip>
#include <unordered_set>
#include "ResidueSystem.h"
#include "CompositeFilter.h"
#include "MaximalPrimeGenerator.h"
#include "PrimeComparator.h"
#include "GoldbachTester.h"

int main() {
    while (true) {
        std::cout << "\n=== [510510 Maximal Prime System] ===\n";
        std::cout << "1. Compare with sieve in a given range\n";
        std::cout << "2. Generate primes only in a given range\n";
        std::cout << "3. Return to menu\n";
        std::cout << "4. Exit\n";
        std::cout << "5. Goldbach test for odd numbers\n";
        std::cout << "Choose an option: ";

        int choice;
        std::cin >> choice;

        if (choice == 1 || choice == 2 || choice == 5) {
            unsigned long long upperBound;
            std::cout << "Enter upper bound: ";
            std::cin >> upperBound;

            // 🕒 تقدير الوقت المتوقع
            unsigned long long estimatedSeconds = (upperBound / 1000000) * 2;
            if (estimatedSeconds < 10) estimatedSeconds = 10;
            if (estimatedSeconds > 3600) estimatedSeconds = 3600;

            unsigned long long minutes = estimatedSeconds / 60;
            unsigned long long seconds = estimatedSeconds % 60;

            std::cout << "\n🕒 Estimated time for full analysis: ";
            if (minutes > 0)
                std::cout << minutes << " minute(s) and " << seconds << " second(s).\n";
            else
                std::cout << seconds << " second(s).\n";

            ResidueSystem rs;
            MaximalPrimeGenerator generator(rs);
            auto primes = generator.generateUpTo(upperBound);

            if (choice == 1) {
                PrimeComparator comparator;
                auto reference = comparator.generateReferencePrimes(upperBound);
                double matchRatio = comparator.compare(primes, reference);

                std::cout << "\n[Comparison Report]\n";
                std::cout << "Range: 1 to " << upperBound << "\n";
                std::cout << "Generated by maximal method: " << primes.size() << "\n";
                std::cout << "Generated by sieve: " << reference.size() << "\n";
                std::cout << std::fixed << std::setprecision(4);
                std::cout << "Match ratio: " << matchRatio << "%\n";

                if (matchRatio < 100.0) {
                    comparator.printMissing(primes, reference);
                }
                else {
                    std::cout << "✓ All reference primes were successfully generated.\n";
                    std::cout << "Note: Sieve used only for verification. Maximal method is the primary generator.\n";
                }

                // ✅ اختبار غولدباخ
                GoldbachTester tester;
                int passedOddPrimes = tester.countOddPrimeRepresentations(primes);
                int totalOddPrimes = 0;
                for (auto p : primes) {
                    if (p >= 7 && p % 2 == 1) ++totalOddPrimes;
                }

                int passedOddNonPrimes = tester.countOddNonPrimeRepresentations(primes, upperBound);
                int totalOddNonPrimes = 0;
                std::unordered_set<unsigned long long> primeSet(primes.begin(), primes.end());
                for (unsigned long long n = 9; n <= upperBound; n += 2) {
                    if (!primeSet.count(n)) ++totalOddNonPrimes;
                }

                double ratio1 = 100.0 * passedOddPrimes / totalOddPrimes;
                double ratio2 = 100.0 * passedOddNonPrimes / totalOddNonPrimes;

                std::cout << "\n[Goldbach Test Summary]\n";
                std::cout << "Odd primes tested: " << totalOddPrimes << ", passed: " << passedOddPrimes
                    << ", success ratio: " << std::fixed << std::setprecision(4) << ratio1 << "%\n";
                std::cout << "Odd non-primes tested: " << totalOddNonPrimes << ", passed: " << passedOddNonPrimes
                    << ", success ratio: " << std::fixed << std::setprecision(4) << ratio2 << "%\n";

            }
            else if (choice == 2) {
                std::cout << "\n[Generated Primes up to " << upperBound << "]\n";
                for (auto p : primes) {
                    std::cout << p << "\n";
                }

            }
            else if (choice == 5) {
                GoldbachTester tester;
                tester.testOddPrimes(primes);
                tester.testOddNonPrimes(primes, upperBound);
            }

        }
        else if (choice == 3) {
            continue;
        }
        else if (choice == 4) {
            std::cout << "Exiting...\n";
            break;
        }
        else {
            std::cout << "Invalid choice. Try again.\n";
        }
    }

    return 0;
}
